### ISSUE TITLE
Calibration Firmware Mini 3 Pro

### ISSUE THREAD

**Issue by moinmoin68** [cs2000/DankDroneDownloader#26]
Hello need calibrtion firmware for AR 5 for mini 3 pro? Is it available?

**Comment by moinmoin68** [comment]
Now i have this Software. If you want @cs2000 i can give to you to publish on DDD.

**Comment by cs2000** [comment]
Sorry i dont have that file, everything i have is always visible in the app. However if you do have it, it would be amazing if you wanted to upload it somewhere and let me have a link! If you cannot upload the full file due to size limits, just open the .bin file in 7-zip and inside will be a file ending in .cfg.sig, just upload then and i can recreate the FW binary from that.

**Comment by ZeroNotHero** [comment]
Any news on this? Im working on another M3P. Thanks guys!

**Comment by cs2000** [comment]
Nothing sadly, I’ve not heard from @moinmoin68

**Comment by moinmoin68** [comment]
> Nothing sadly, I’ve not heard from @moinmoin68  

Sorry had a lot of work, please Share an email so that i can send Firmware to you

**Comment by cs2000** [comment]
> > Nothing sadly, I’ve not heard from @moinmoin68
> 
> Sorry had a lot of work, please Share an email so that i can send Firmware to you

Sure, send whatever you have to Hawkins.Christopher88@gmail.com and il get it added :)

**Comment by DJOPING** [comment]
I see the firmware in the mini3 slot.
![image](https://user-images.githubusercontent.com/67260342/233843964-21631df4-4791-45e8-9664-2ac64f02efc3.png)

**Comment by ZeroNotHero** [comment]
But not in the Mini 3 Pro slot :(

**Comment by DJOPING** [comment]
@cs2000 Can you change firmware address from channel mini 3 to mini 3 pro?

**Comment by cs2000** [comment]
All swapped to the Mini 3 Pro, sorry for the mixup!
