### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by vinc13008** [cs2000/DankDroneDownloader#27]
Hello ! 

Looks like the app can"t connect to server anymore. Are server down ?

Anyway, keep it up the fantastic work you do ! <3

**Comment by cs2000** [comment]
Hey, yes im so sorry for this. The server suffered a failure of the secondary drive, before the hosts could replace this, the primary drive also failed which resulted in a non-operational server. I have been working on this ever since.

Please keep an eye on the status page i have set up for more updates. https://dddstatus.com

I sincerely apologize for the inconvenience!
