### ISSUE TITLE
ARB 6 calibration for mini 3 pro 

### ISSUE THREAD

**Issue by BicThor** [cs2000/DankDroneDownloader#34]
Hello everyone. Have anyone got that firmware? Thank you

**Comment by SuiCxDe007** [comment]
@BicThor could you please explain what is ARB6 calibration? After gimbal replacement my mini 3 pro gimbal is not working properly and calibration fails through the app

**Comment by BicThor** [comment]
Hello @SuiCxDe007, sorry for answering too late. As I know there are calibration firmwares to calibrate the drones, one for each firmware version. I have the same problem as you and I am waiting for the calibration firmware for the 1.06 version

**Comment by SuiCxDe007** [comment]
> Hello @SuiCxDe007, sorry for answering too late. As I know there are calibration firmwares to calibrate the drones, one for each firmware version. I have the same problem as you and I am waiting for the calibration firmware for the 1.06 version

Thanks for the update. During waiting i sent a message to some guy who was telling that he can fix it remotely. He charges 20$. However he connected to my laptop and did the calibration remotely but mine didn't work because of a cable issue. Going to try with him again once the cable comes. However, i really hope we can find the required firmware for mini 3 series

**Comment by cs2000** [comment]
No sign of an ARB 6 calibration firmware yet. Il leave the discussion here open, but if/when it does come my way, it will be added to DDD
