### ISSUE TITLE
Windows Security Center reports a threat.

### ISSUE THREAD

**Issue by gaifeng8864** [cs2000/DankDroneDownloader#37]
After the latest version of the program (V3.0 Build 8666.1215) started running, Windows Security Center reported a threat. This has never happened in previous versions.

**Comment by cs2000** [comment]
Hey, I talked about this on the readme, il copy the text here for you. I have submitted the app to Microsoft as a false positive, their reporting system agrees it is not a threat, but it needs a defender signature update to stop it being detected which can take a little time.

I have been informed that some AV apps occasionally flag DDD as malware of various forms. This is caused by the way that some components of the EXE are packed to reduce filesize of the app itself

It is only obscure, non mainstream apps that report this and are of course false positives. Rest assured nothing nefarious is going on! I will try to remember (i am human) to update the link below with results for the current app version.

https://www.virustotal.com/gui/file-analysis/YjhjNDRiM2EzZGRjN2ViNTc2YTI5N2IzNGE4YWJhYWU6MTY5NTQyNjgzOA==
