### ISSUE TITLE
Unautorized Error while opening app

### ISSUE THREAD

**Issue by aytacengin** [cs2000/DankDroneDownloader#39]
![image](https://github.com/cs2000/DankDroneDownloader/assets/16681354/a4426383-fe16-481e-9614-274a8b657281)

I have always same error on my screen. What is problem ? Could you fix it ?

**Comment by cs2000** [comment]
It’s a generic error that just means the response your client sent to the server wasn’t correct, it’s all to do with server security.

Generally it can be resolved by restarting, making sure any firewall or antivirus apps have exceptions in place for DDD and crucially **making sure your system clock is correct**, again, due to system security, I have a time limit on the server of requests being 15 seconds off of the official system time (UTC) before they are rejected, so make sure your system time is synced with an NTP time server.

**Comment by aytacengin** [comment]
All Firewall swich off. And ı am not using any antivirus apps. Time settings is correct. Internet Connection is 500 Mbits. Everything is okay. So I am using many application with Server connection. There is no error. I am from Turkey. Is there any IP limit ? Could you check your server. Because of, In Istanbul, our comunity many people can not use DankDroneDownloader app. Not only our computer..
