### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by Q-Diddy** [cs2000/DankDroneDownloader#51]
Running windows 10 pro and the following error occurs at start of launching the app.![image](https://github.com/user-attachments/assets/7a679456-2ceb-40e7-995d-53a243dc3332) here is what the error log says... ![image](https://github.com/user-attachments/assets/81920d0a-3f3b-4e20-83e5-3b33c8098e4c) I noticed this happen after windows 10 pro updated .net but can't seem to roll it back.

**Comment by cs2000** [comment]
Thanks for the message, i now have 2 reports of this happening since Friday so clearly something in one of those updates has broken DDD. 

Il have to set up a windows 10 test machine and run some tests, but hopefully i can find the cause and get an update out to fix it.

Leave it with me, i am checking

**Comment by cs2000** [comment]
This bug should now be fixed. Please download the latest version from the releases page of GitHub.
